### ISSUE TITLE
Flipping normals

### ISSUE THREAD

**Issue by vulture-boy** [ologon/Sprytile#10]
![image](https://user-images.githubusercontent.com/19735946/83341173-53133b80-a2ae-11ea-8510-bafb15892439.png)

At the moment, when drawing with the build tool, planes are lain out in the typical two-right-triangles fashion. So when you lift the verticies in the middle of a painted square or rectangle of these, you have the effect where the planes are bent at this seam. This can be problematic for issues where you want a cleanly bordered plateau. 

In Crocotile, this can be easily fixed by reversing the normals; I would love to have a similar function where you can reverse the normals for a particular tile, since it doesn't seem possible to do in Blender at the moment without erasing the tile(s), changing the view orientation, then drawing the tiles again.

**Comment by ologon** [comment]
If you need to flip the normals, it can be done using blender's standard mesh tools. Select the tile you want to flip and hit Mesh -> Normals -> Flip in the top right menu.

**Comment by vulture-boy** [comment]
That doesn't actually work, I've already tried that.

**Comment by ologon** [comment]
Actually it should work:

Before:
![2020-06-01_11h41_09](https://user-images.githubusercontent.com/30046703/83371283-0722dc80-a3fd-11ea-8c24-34188cf6ac7e.png)

After flipping the selected tile normals:
![2020-06-01_11h41_45](https://user-images.githubusercontent.com/30046703/83371316-17d35280-a3fd-11ea-8e7d-1eca959216b2.png)

As you can see the normal for the tile is flipped. Note that the material sprytile uses by default is double-faced so you won't see a difference in the appearance (The UVs remain the same). If you want to flip the UVs you can use FlipX/FlipY in the sprytile panel.

**Comment by ologon** [comment]
Also please note that if you intend to lift the verteces of the tiles like in the image of your post, you should explicitly cut the face in two triangles depending on what you want to achieve, using the knife tool, or you may get unexpected result (as sprytile uses quads, not triangles):

Bad example:
![2020-06-01_14h22_21](https://user-images.githubusercontent.com/30046703/83378403-93d89500-a413-11ea-8e07-e8f6810763aa.png)

Good example1:
![2020-06-01_14h23_02](https://user-images.githubusercontent.com/30046703/83378418-9affa300-a413-11ea-8492-3a90c838ae6c.png)

Good example2:
![2020-06-01_14h24_05](https://user-images.githubusercontent.com/30046703/83378425-a18e1a80-a413-11ea-8e85-461c16f2bdd6.png)

Hope that helps!

**Comment by vulture-boy** [comment]
Did you try flipping the UVs of a corner? That is what I was having issues with. In crocotile, I dont need to split anything to accomplish this.

**Comment by ologon** [comment]
Yes, I don't have particular problems if I understood correctly your problem:

(The top left tile has X/Y UVs flipped)
![2020-06-01_15h16_38](https://user-images.githubusercontent.com/30046703/83381274-35afb000-a41b-11ea-91b4-5cffd2485bbd.png)

**Comment by vulture-boy** [comment]
Right, but this is a flat surface again.
Im specifically addressing the case where a vertex has been raised in a corner.
I might be explaining things badly or using the wrong terminology admittedly but so far I dont think we're on the same page...

**Comment by vulture-boy** [comment]
i.e. draw four, lift the center vertex in Z, then flip the quad geometry so it looks like a clean point.

**Comment by ologon** [comment]
As I said above, if you lift the center vertex in Z, you end up with non-coplanar quads which don't have a defined behaviour, so you have to slice them with the knife tool (I don't have crocotile, but maybe it works with triangulated quads to begin with)

**Comment by vulture-boy** [comment]
So there's no way of switching a quad between what visually looks like your "good example" 1 & 2 without slicing it? 
Im able to get the effect I want with these quads by just rotating my view when I place the corner quad elements before lifting the vertex (as I did in the original image), so I suppose I am confused why I can't just switch between these two behaviours for the quad.

**Comment by vulture-boy** [comment]
Found a solution that works for me...
Ctrl-T -> Triangulate Faces
- Select between quad method: fixed or fixed alternate depending on desired quad division
Alt J -> Tris to Quads
The quad will now lift as desired!

**Comment by ologon** [comment]
Glad you found a solution! However I wouldn't recommend doing it that way, because as I said, with non-coplanar quads blender doesn't really know how it should triangulate it if you don't triangulate it explicitly. With the above method you are "forcing" it, but you will likely run into issues if you try to export the model to other software, so I would recommend keeping the quad triangulated (No Alt-J)

I am closing this issue. Happy modelling!

**Comment by vulture-boy** [comment]
Noted! I'll keep that in mind if I do have any issues, but so far it works fine for Unity (.obj)

**Comment by vulture-boy** [comment]
Probably worth keeping in mind on your end that triangulating the quad makes the triangles treated as seperate for painting purposes, so triangulation should really only be applied at the end in this case if you want the ability to paint the tile as a single element.
