### ISSUE TITLE
Fill with Lock Transforms causes crash

### ISSUE THREAD

**Issue by vulture-boy** [ologon/Sprytile#11]
Filling an empty area with Lock Transforms enabled causes an error report, followed by a crash after about 10 seconds. Not sure if this applies to other fill areas.

![image](https://user-images.githubusercontent.com/19735946/83341290-c23d5f80-a2af-11ea-90ce-751a7307da7e.png)

**Comment by ologon** [comment]
This bug was addressed in beta10. Thanks for the report!
