### ISSUE TITLE
unable to enable addon

### ISSUE THREAD

**Issue by luntik2012** [ologon/Sprytile#12]
![image](https://user-images.githubusercontent.com/8270543/83346060-0ec18300-a322-11ea-990b-6439eeb70562.png)

**Comment by ologon** [comment]
Please make sure sprytile was installed correctly. First uninstall the current version and make sure  there's no trace of it in C:\Users\spadafina_alfredo\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons. Restart blender, then install again the latest version of sprytile (beta9)

**Comment by vulture-boy** [comment]
I've had this issue too. It happens when another instance of sprytile was installed on blender. Uninstall, restart blender, install and it should work!

**Comment by ologon** [comment]
I am closing this issue as unable to reproduce. If you need further help, please leave a comment!
