### ISSUE TITLE
View for detecting single-sided quads

### ISSUE THREAD

**Issue by vulture-boy** [ologon/Sprytile#13]
Hello! Feature request!
Would it be possible for there to be a view that allows users to see quads in the viewport without them visually appearing double-sided? i.e. just showing the quads visible from the side that they are actually visible from? 
In crocotile, this is the default view; would be super handy to be able to flip between the two.

**Comment by ologon** [comment]
What you are looking for is backface culling. Enabling it in the object material will do the trick!
![キャプチャ](https://user-images.githubusercontent.com/30046703/83705247-6841ee80-a64f-11ea-8b7f-9a739879cfd7.PNG)

**Comment by vulture-boy** [comment]
Thanks!

**Comment by ologon** [comment]
Yep blender is a very powerful full blown 3d software, so usually there's an option for everything (it's easy to get lost at first). Sprytile just sits on top of its tools. (which is also kind of its strength)
