### ISSUE TITLE
Exported models lack textures

### ISSUE THREAD

**Issue by vulture-boy** [ologon/Sprytile#14]
Hello again!
I've tried exporting models in both .fbx and .obj and both formats seem to export geometry fine (including those quads we talked about earlier, they work fine w/o triangles) but do not bring the texture along with them.

I've tried importing the models into Blender, Unity and Rhinoceros to test. No dice!

Since i've used the same texture image for crocotile models, I tried adding the crocotile mtl to the exported object and it works perfectly, so I'm assuming it's just a matter of binding the image to the file.

**Comment by ologon** [comment]
Model formats like fbx and obj don't export textures with them, they just contain the UV coordinates. You have to import the textures as well and set the materials for them (How you do that depends on the software you are using). For more details, see here: https://blender.stackexchange.com/questions/57531/fbx-export-why-there-are-no-materials-or-textures

**Comment by vulture-boy** [comment]
Weird that the option isnt available! Im used to Rhinoceros and Crocotile doing it by default, which seems like it would be fine for this implementation?

**Comment by ologon** [comment]
Yeah, blender doesn't have an option to automatically copy the textures over afaik, so you have to manually copy them. (Maybe the rationale is that Rhinoceros/Crocotile don't have complex node based materials like blender does, so it makes more sense for them to export textures by default)
