### ISSUE TITLE
Discord tag

### ISSUE THREAD

**Issue by CheedoCreations** [ologon/Sprytile#6]
Hello there, do you use discord? If so is it okay to share it because i do have crashes after time on blender with the plugin on 2.80 or sudden pallet disappearance, i really do like and still use this plugin to this day and i want to do my best to improve it, if you read this thank you for bringing sprytile to 2.8!

**Comment by ologon** [comment]
Hi!
I don't use discord much, but if you want to help with crashes you can attach crash logs here and steps to reproduce, I will look into it when I have time :)
To get crash logs, you can follow this method I posted here: https://itch.io/post/1054262

Also, regarding palette disappearing see here: https://itch.io/post/1158224

Hope that helps!

**Comment by CheedoCreations** [comment]
Yes! i had to restart my blender countless times already!
