### ISSUE TITLE
Another question

### ISSUE THREAD

**Issue by CheedoCreations** [ologon/Sprytile#7]
For a few days, i have been wondering where the original developers went for sprytile, the tool itself is so good but i was devastated that the tool hasn't been updated for almost 2 years, im happy that this tool is open source and developers who ported it over to 2.8 like you ologon is so much of a blessing.
aside from crashes or sudden issues that may not have the great quality of life scenarios im happy to see this tool forked to 2.8, however i still don't know why and how the developer originally made sprytile went? is there an explanation of whats been going on and if we're ever going to see any future made with sprytile? thank you if you reply, i have been wondering about this case for several months and i want to speak out about it of the future of sprytile, thank you if you reply and thank you again for porting this tool, i've never stopped using it for the longest time and i sincerely hope for the better of the community of sprytile

**Comment by ologon** [comment]
Thanks! I don't know what the intentions are for the original sprytile, maybe you could try asking in the official forums or github? Unfortunately for OS (especially solo) projects usually there are up and downs depending on personal free time, life, projects.. they can become hard to maintain at times. (I just luckily happened to have enough time to port it this time around)

**Comment by CheedoCreations** [comment]
Thanks for replying, i will try to ask around the forums or something
