### ISSUE TITLE
Hotkeys (rotation, flipping, etc?)

### ISSUE THREAD

**Issue by vulture-boy** [ologon/Sprytile#8]
Hello!

In the original Sprytile, there were hotkeys for rotating and flipping tiles. Are they available in 2.8? If so,  would it be possible to implement a feature to add them when the Sprytile tools are active?

My current solution is to just use Quick Favourites.

**Comment by ologon** [comment]
Hi!

Unfortunately, the hotkeys are not implemented in 2.8 yet. (As you pointed out the current workaround is to use quick favourites)

**Comment by ologon** [comment]
Hotkeys for rotating and flipping tiles are now available in beta10 (4,5,6,7 keys)
